Repository domhankle/server-duels, pull requests merged in 2024-01, with the labels that each got.

#5 PR Template - DUELS-10
  .github/pull_request_template.md
Labels: feature

#4 Adding License - DUELS-4
  LICENSE.md
Labels: feature, dependency

#1 DUELS-3 Create README.md
  README.md
Labels: feature, parent

#6 v0.1 Release
  .github/pull_request_template.md
  .gitignore
  LICENSE.md
  README.md
  pyproject.toml
  scripts/.gitkeep
  src/.gitkeep
  tests/.gitkeep
Labels: release
