Repository domhankle/server-duels, pull requests merged in 2024-02, with the labels that each got.

#8 Vic DUELS-11 Adding dependency bash script
  scripts/get_dependencies.sh
Labels: feature, dependency

#10 Vic DUELS-23 update dependency script
  scripts/get_dependencies.sh
Labels: feature

#11 Revert "Vic DUELS-23 update dependency script"
  scripts/get_dependencies.sh
Labels: bug

#7 Auto Env Setup Script - DUELS-12
  scripts/env_setup.sh
Labels: feature, parent

#14 fixing the weird unmatching dependency file DUELS-23
  scripts/get_dependencies.sh
Labels: feature
